ProyectoInfo2022/apps/AppBlog/urls.py
from django.urls import path

from .views import frontpage, post_detail, banners

urlpatterns = [
    path('',frontpage, name='index'),
    path('<slug:slug>/', post_detail, name='post_detail'),
    path('blog.html', banners,name='blog'),
]

ProyectoInfo2022/apps/AppUsers/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login.html', views.login, name='login'),
    path('logout.html', views.logout, name='logout'),
]

ProyectoInfo2022/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView 

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # Posts y comentarios
    path('', include(('ProyectoInfo2022.apps.AppBlog.urls', 'AppBlog'), namespace='posts')),
    # Usuarios
    path('', include(('ProyectoInfo2022.apps.AppUsers.urls', 'AppUsers'), namespace='usuarios')),
    # Acerca de...
    path(
        route='about.html',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    # Contacto
    path(
        route='contact.html',
        view=TemplateView.as_view(template_name='contact.html'),
        name='contact'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ProyectoInfo2022/apps/AppBlog/models.py
from django.db import models

# Create your models here.
from ckeditor.fields import RichTextField


#....
class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    imagen = models.ImageField(upload_to='posts/imagenes', default='')
    intro = RichTextField()
    body = RichTextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']
    
    def __str__(self):
        return self.title

ProyectoInfo2022/apps/AppUsers/models.py
from django.db import models

# Create your models here.

ProyectoInfo2022/apps/AppBlog/views.py
from django.shortcuts import redirect, render

from .models import Post
# Create your views here.
 

def frontpage(request):
    posts = Post.objects.all()

    return render(request, 'posts/index.html', {'posts':posts})

def banners(request):
    posts = Post.objects.all()

    return render(request, 'posts/blog.html', {'posts':posts})

def post_detail(request, slug):
    post = Post.objects.get(slug=slug)

    return render(request, 'posts/detail.html', {'post': post})

ProyectoInfo2022/apps/AppUsers/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.contrib import messages
from django.contrib.auth.models import User, auth


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Contraseña inválida.')
            return redirect('/login.html')

    else:
        return render(request, 'usuarios/login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')

ProyectoInfo2022/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Contenido de página -->
<title>Quienes somos</title>
<!-- Banner: Inicio-->
<div class="heading-page header-text">
  <section class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-content">
            <h4>QUIENES SOMOS</h4>
            <h2>Conocenos mejor...</h2>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Banners: fin -->

<section class="about-us">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <img src="{% static 'assets/images/about-us-2.jpg' %}" alt="" max width="50%">
        <br></br>
        <h5>MISIÓN</h5>
        <p>Promover el intercambio cultural y el desarrollo humano a través de la educación, la palabra y la música,
          favoreciendo la inclusión de niños, jóvenes y adultos en situación de riesgo. Utilizar el arte y el lenguaje
          como pilares fundamentales. Promover y profundizar el estudio de la música como una alternativa creadora, de
          disciplina personal y proyecto de vida, que brinde posibilidades a los jóvenes ayudándolos a profesionalizar
          el arte y adoptándolo como medio de vida. Impulsar la creación de orquestas infantiles y juveniles entendiendo
          estos espacios como una herramienta de transformación social.</p>
        <h5>HISTORIA</h5>
        <p>El proyecto nace el 11 de noviembre de 2007 con clases de música, en donde se enseña teoría musical,
          instrumentos de viento y percusión. El 6 de septiembre de 2008, arranca como banda de música y realiza su
          primera presentación en público en el Encuentro de Danzas Españolas en el teatro Ateneo de la provincia Roque
          Saenz Peña, invitados por la señora Alicia Gaña. En noviembre del 2010, se comienza a dar clases de cuerdas
          (violín, violonchelo, contrabajo, viola). Desde ese momento, se transforma el conjunto en Orquesta.
          Actualmente, cuenta con 82 alumnos y la Orquesta con 50 integrantes. Además, cuenta con un programa de
          voluntariado internacional de música, que consiste en la visita de jóvenes de distintos países del mundo de
          orquestas profesionales que vienen a dictar clases de música. Eso ha permitido el crecimiento de la escuela y
          la orquesta.</p>
        <h5>RESPONSABLES</h5>
        <p>Ricardo Velazquez, Gonzalo Cejas y Nilce Bravo.</p>
      </div>
    </div>

    <!--div class="row">
      <div class="col-lg-6">

        <h4>Dos columnas: más información</h4>
        <p>Agregar mas info</p>
      </div>
      <div class="col-lg-6">
        <h4>Dos columnas: más información</h4>
        <p>Agregar mas info</p>
      </div>
    </div-->
  </div>
</section>

{% endblock %}

ProyectoInfo2022/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <meta name="description" content="">
  <meta name="" content="">
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link
    href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
    rel="stylesheet">

  <title>Fundación Vientos de Cambio</title>
  <link rel="icon" href="{% static 'assets/images/logo_vtos_cambio.JPG' %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


  <!-- Archivos adicionales CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/templatemo-stand-blog.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">

  <!-- nav-tab -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <link rel="icon" href="{% static 'favicon.ico' %}">

</head>

<body>

  <!-- ***** Precargador: inicio ***** -->
  <div id="preloader">
    <div class="jumper">
    </div>
  </div>
  <!-- ***** Precargador: fin***** -->
  <!--barra social-->
  <div class="fabs" onclick="toggleBtn()">
    <div class="action">
      <i class="fas fa-plus" id="add"></i>
      <i class="fas fa-times" id="remove" style="display: none"></i>
    </div>

    <div class="btns">
      <a href="https://www.facebook.com/orquestavientosdecambio" class="btn" target="_blank"
        style="background: #3b5999"><i class="fab fa-facebook-f"></i></a>
      <a href="https://api.whatsapp.com/send?phone=3644574664" class="btn" target="_blank"
        style="background: #25D366"><i class="fab fa-whatsapp"></i></a>
      <a href="https://www.instagram.com/fvientosdecambio" class="btn" target="_blank" style="background:#e4405f"><i
          class="fab fa-instagram"></i></a>
    </div>
  </div>
  <!--finsocial-->

  <!-- Header -->
  <header class style="top:0;">
    <nav class="navbar navbar-expand-lg">
      <div class="container">
        <!--LOGO FUNDACIÓN VIENTOS DE CAMBIO-->
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <h2><img src="{% static 'assets/images/logo_vtos_cambio.JPG' %}" max width="40%"><em></em></h2>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
          aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:index' %}">INICIO<span class="sr-only"></span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">QUIENES SOMOS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:blog' %}">ÚLTIMAS NOTICIAS</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">CONTACTO</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="../admin/" style="color:rgb(5, 161, 0)">ADMINISTRAR SITIO</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuarios:logout' %}" style="color:#e4405f">SALIR</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'usuarios:login' %}">INGRESAR</a>
            </li>
            {% endif %}

          </ul>
        </div>
      </div>

    </nav>

  </header>


  {% block content %}

  {% endblock %}

  <footer>
    <div class="container">
      <div class="row mb-3">
        <!--aside>
          <div class="col-8">
            <div class="widget">
              <img src="{% static 'assets/images/logo_vtos_cambio_fondo_pagina.png' %}" max width="150px">
            </div>
          </div>
        </aside-->
        <!--div class="col-7">
          <div class="widget">
            <p style="text-align:center;">Integrantes</p>
          </div>
        </div-->
      </div>
    </div>

    <div class="container">
      <!--div class="row">
        <div class="col-lg-12">
          <p style="text-align:center;"> Encontranos en nuestras redes &nbsp;
          <ul class="social-icons">
            <li>
              <title>Icon-fb</title>
              <link rel="stylesheet" href="{% static 'assets/css/estilo.css' %}">
              <script src="https://cdn-icons-png.flaticon.com/512/145/145802.png" crossorigin="anonymous"></script>

              <body>
                <a href="https://www.facebook.com/orquestavientosdecambio" class="fa fa-facebook" target="_blank"></a>

              </body>
            </li>

            <li>
              <title>Icon-WhatsApp</title>
              <link rel="stylesheet" href="{% static 'assets/css/estilo.css' %}">
              <Icon-Font>
              <script src="https://kit.fontawesome.com/eb496ab1a0.js" crossorigin="anonymous"></script>

              <body>
                <a href="https://api.whatsapp.com/send?phone=3644574664" class="fa fa-whatsapp icono" target="_blank">
                </a>
              </body>
            </li>

            <li><a href="https://www.instagram.com/fvientosdecambio" class="fa fa-instagram" target="_blank"></a></li>
          </ul>
          </p>
        </div-->
      <div class="col-lg-12">
        <p style="text-align:center">Colabora con nosotros &nbsp;
          <link rel="stylesheet"
            href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
          <a href="https://donaronline.org/fundacion-vientos-de-cambio/aporte-solidario-orquesta-escuela-vientos-de-cambio?fbclid=IwAR1HdE7hAHcrN_7azsP41KjBC2K_D3Y0ezo6pMcgLp1SZ4dymmcNg53MUs8"
            target="_blank"><i class="fa fa-credit-card" aria-hidden="true"></i></a>
        </p>
      </div>
      <div class="col-lg-12">
        <div class="copyright-text">
          <p>© Copyright 2022 | Design by <a rel="nofollow" href="" target="_parent">Grupo 6 - Informatorio 2022</a></p>
          <p style="color: beige;">Integrantes</p>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <p style="text-align:center;"><a rel="nofollow" href="https://www.linkedin.com/in/ismael-h-531812238" target="_parent">Ismael Hernan</a> |<a rel="nofollow" href="https://www.linkedin.com/in/matias-ezequiel-palacio-5728b9249/" target="_parent"> Matias Ezequiel Palacio </a>| Carolina Graciela Marturet |
              <a rel="nofollow" href="https://www.linkedin.com/in/alexander-ariel-moreira-0b866a56" target="_parent">Alexander Ariel Moreira </a>| Selene Gomez | Bruno Damian Acuña</p>
          </div>
        </div>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Scripts Adicionales-->
  <script src="{% static 'assets/js/custom.js' %}"></script>
  <script src="{% static 'assets/js/owl.js' %}"></script>
  <script src="{% static 'assets/js/slick.js' %}"></script>
  <script src="{% static 'assets/js/isotope.js' %}"></script>
  <script-- src="{% static 'assets/js/accordions.js' %}"></script>

  <script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0;
    function clearField(t) {
      if (!cleared[t.id]) {
        cleared[t.id] = 1;
        t.value = '';
        t.style.color = '#fff';
      }
    }
  </script> 

</body>
<script>
  function toggleBtn() {
    const Btns = document.querySelector(".btns");
    const add = document.getElementById("add");
    const remove = document.getElementById("remove");
    const btn = document.querySelector(".btns").querySelectorAll("a");
    Btns.classList.toggle("open");
    if (Btns.classList.contains("open")) {
      remove.style.display = "block";
      add.style.display = "none";
      btn.forEach((e, i) => {
        setTimeout(() => {
          bottom = 40 * i;
          e.style.bottom = bottom + "px";
          console.log(e);
        }, 100 * i);
      });
    } else {
      add.style.display = "block";
      remove.style.display = "none";
      btn.forEach((e, i) => {
        e.style.bottom = "0px";
      });
    }
  }
</script>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v14.0"
  nonce="kSW5OqyE"></script>

</html>

ProyectoInfo2022/templates/posts/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Contenido -->
<!-- Publicaciones -->
<div class="heading-page header-text">
  <section class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-content">
            <marquee behavior="scroll" direction="right" scrolldelay="400">
              <h2><b>Noticias &#127991;</b></h2>
            </marquee>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<!-- Publicaciones: fin -->

<section class="blog-posts grid-system">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="all-blog-posts">
          <div class="row">
            {% for post in posts %}
            <div class="col-lg-6">
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="{{ post.imagen.url }}" height: 100px; alt="">
                </div>
                <!--<div class="down-content"> (1)-->

                <a href="{% url 'posts:post_detail' post.slug %}">
                  <h4>{{ post.title }}</h4>
                </a>
                <ul class="post-info">
                  <li><a href="#">{{ post.date_added }}</a></li>
                </ul>
                <p>{{ post.intro|safe }}</p>
                <!--ETIQUETAS
                  <div class="post-options">
                    <div class="row">
                      <div class="col-lg-6">
                        <ul class="post-tags">
                          <li><i class="fa fa-tags"></i></li>
                          <li><a href="#">Tags</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  -->
                <!--</div>-->
              </div>
            </div>
            {% endfor %}

</section>

{% endblock %}

ProyectoInfo2022/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Contenido -->
<title>{{ post.title }}</title>
<!-- Banner: inicio -->
<div class="heading-page header-text">
  <section class="page-heading">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="text-content">
            <h2>{{ post.title }}</h2>
            <ul class="post-info">
              <li><a href="#">{{ post.date_added }}</a></li>
            </ul>
            <h2></h2>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!-- Banner: fin -->

<!--POST EN DETALLE-->
<section class="blog-posts grid-system">
  <div class="container">
    <div class="row">
      <div class="col-lg-10">
        <div class="all-blog-posts">
          <div class="row">
            <div class="col-lg-12">
              <div class="blog-post">
                <div class="blog-thumb">
                  <img src="{{ post.imagen.url }}" alt="">
                </div>
                <!--<div class="down-content"> (1)-->
                <!--
                <div class="text-content">
                  <h4>{{ post.title }}</h4>
                  <h2></h2>
                </div> -->

                <!--<a href="{% url 'posts:post_detail' post.slug %}"></a>-->

                <!--Aquí estaba anteriormente la fecha-->


                <p>{{ post.body|safe }}</p>
                <!--ETIQUETAS
                  <di class="post-options">
                    <div class="row">
                      <div class="col-6">
                        <ul class="post-tags">
                          <li><i class="fa fa-tags"></i></li>
                          <li><a href="#">Etiquetas</a></li>
                        </ul>
                      </div>
                    </div>
                  </di>
                  -->
                <!--</div> (1)-->
              </div>
            </div>

          </div>

          <!--BOTONES DE FACEBOOK-->
          <p>
          <ul>
            <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-width="" data-layout="button"
              data-action="like" data-size="large" data-share="true"></div>
          </ul>
          </p>


          <!--COMENTARIOS CON FACEBOOK-->
          <div class="col-lg-12">
            <div class="sidebar-heading">
              <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-width="" data-numposts="5">
              </div>
            </div>
          </div>
        </div>
</section>
{% endblock %}

ProyectoInfo2022/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--------------------------------------
HEADER
--------------------------------------->
<div class="container">
	<div class="jumbotron jumbotron-fluid mb-3 pt-0 pb-0 bg-lightblue position-relative">
		<div class="pl-4 pr-0 h-100 tofront">
			<div class="row justify-content-between">
				<div class="col-md-6 pt-6 pb-6 align-self-center">
					<h1 class="secondfont mb-3 font-weight-bold">MISIÓN</h1>
					<p class="mb-3">
						Promover el intercambio cultural y el desarrollo humano a través de la educación, la palabra y la música, favoreciendo la inclusión de niños, jóvenes y adultos en situación de riesgo. Utilizar el arte y el lenguaje como pilares fundamentales. Promover y profundizar el estudio de la música como una alternativa creadora, de disciplina personal y proyecto de vida, que brinde posibilidades a los jóvenes ayudándolos a profesionalizar el arte y adoptándolo como medio de vida. Impulsar la creación de orquestas infantiles y juveniles entendiendo estos espacios como una herramienta de transformación social.
					</p>
					<a href="{% url 'about' %}" class="button">Leer Más</a>
				</div>
				<div class="col-md-6 d-none d-md-block pr-0"><img src="{% static 'assets/images/about-us-2.jpg' %}" ></div>
			</div>
		</div>
	</div>
</div>
<!-- End Header -->
<!--------------------------------------
MAIN
--------------------------------------->
    
<div class="container pt-4 pb-4">
	<div class="row">
		<div class="col-lg-6">
			<div class="card border-0 mb-4 box-shadow h-xl-300">              
                <div style="background-clip: border-box; height: 50px;    background-size: cover;    background-repeat: no-repeat;"></div>               
				<div class="card-body px-0 pb-0 d-flex flex-column align-items-start">
					<h2 class="h4 font-weight-bold">
					<a class="text-dark" href="https://www.univision.com/explora/los-beneficios-de-la-musica-clasica-en-el-cuerpo" >Los beneficios de la música clásica en el cuerpo</a>
					</h2>
					<p class="card-text">
						Siempre hemos escuchado de los múltiples beneficios de la música clásica en el cuerpo tras la escucha prolongada y habitual de una melodía. Estudios han demostrado la mejora en las respuestas de crecimiento de plantas a las que se pone música clásica.
						Muchas veces al escuchar una música predilecta, muchos de nosotros hemos sentido escalofríos o esa sensación de júbilo indescriptible. Esto se debería a que estimula las mismas áreas del lenguaje y el habla en el córtex cerebral, ya que la música tendría el mismo efecto de calidez que se produce al escuchar una voz humana.
					</p>
					<!--
					<div>
						<small class="d-block"><a class="text-muted" href="./author.html">Favid Rick</a></small>
						<small class="text-muted">Dec 12 &middot; 5 min read</small>
					</div>-->
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="flex-md-row mb-4 box-shadow h-xl-300">
				<div class="mb-3 d-flex align-items-center">
					<div class="pl-3">
						<video width="380" height="320"  muted autoplay>
							<source src="{%static 'fronmusic.mp4'%}" type="video/mp4">
						</video>
					</div>	
				</div>	
			</div>
		</div>
	</div>
</div>
    
<div class="container">
	<div class="row justify-content-between">
		<div class="col-md-8">
			<h5 class="font-weight-bold spanborder"><span>Publicaciones</span></h5>
			
				
					<div class="owl-banner owl-carousel">
			
						{% for post in posts %}
			
						<div class="item">
							<div class="meta-category">
								<a href="{% url 'posts:post_detail' post.slug %}">
								
								<span style="color:rgb(43, 30, 7)">
									<h5><b>
											<center>{{ post.title }}</center>
										</b></h5>
								</span>
							
							
							</div>
							<img src="{{ post.imagen.url }}" alt="" width="300" height="300">
							<div class="item-content">
								<div class="main-content">
			
			
									<a href="{% url 'posts:post_detail' post.slug %}">
										<p></p>
										<button type="submit" class="btn btn-primary"
											style="height:33px;width:87px;line-height: 50px">
											<h6>Leer más</h6>
										</button>
									</a>-->
									
									<ul class="post-info">
										<p></p>
										<p style="color: rgb(255, 255, 255) ;">{{ post.date_added }}</p>
									</ul>
								</div>
							</div>
						</div>
			
						{% endfor %}
					</div>
			
				
			
		</div>
		<div class="col-md-4 pl-4">
            <h5 class="font-weight-bold spanborder"><span>Clips</span></h5>
			<ol class="list-featured">
				<li>
				<span>
				<h6 class="font-weight-bold">
				<a href="https://www.youtube.com/watch?v=FX2qEFLl8WU" class="text-dark">Auténticos Decadentes - LOCO TU FORMA DE SER </a>
				</h6>
				<p class="text-muted">
					Esteban Brizuela (flauta traversa)
					Pablo Petris (clarinete)
					Arreglo: Prof. Ariel Puertas
				</p>
				</span>
				</li>
				<li>
				<span>
				<h6 class="font-weight-bold">
				<a href="https://www.youtube.com/watch?v=4UYqY3z1eD8" class="text-dark">LUCÍA DE ARENA - Orquesta Escuela Vientos de Cambio</a>
				</h6>
				<p class="text-muted">
					Chamamé incluido en el disco "Las Voces de Mi Gente" (1987) compuesto por Zitto Segovia/Marta Quiles.
					Arreglo para orquesta Infantil/Juvenil: Alejandro Ruiz
				</p>
				</span>
				</li>
				<li>
				<span>
				<h6 class="font-weight-bold">
				<a href="https://www.youtube.com/watch?v=yajI0bnYmNY" class="text-dark">El Humauaqueño - Misión Coral Chaco</a>
				</h6>
				<p class="text-muted">
					Orquesta vientos de Cambio
					mayo 17
				</p>
				</span>
				</li>
				<li>
				<span>
				<h6 class="font-weight-bold">
				<a href="https://www.youtube.com/watch?v=Nq8MEu5G6qw" class="text-dark">CHACO SONANDO</a>
				</h6>
				<p class="text-muted">
					3º Encuentro de Orquestas Comunitarias de la Provincia - Pcia. Roque  Sáenz Peña, Chaco. (Julio 2016)
				</p>
				</span>
				</li>
			</ol>
		</div>
	</div>
</div>
    



































<!--Carousel-->
<!--
<div class="main-banner header-text">
    <div class="container-fluid">
        <div class="owl-banner owl-carousel">

            {% for post in posts %}

            <div class="item">
                <div class="meta-category">
                    <!-<a href="{% url 'posts:post_detail' post.slug %}">-->
                    <!--
                    <span style="color:rgb(43, 30, 7)">
                        <h5><b>
                                <center>{{ post.title }}</center>
                            </b></h5>
                    </span>
                    </a>-->
                <!--
                
                </div>
                <img src="{{ post.imagen.url }}" alt="" width="300" height="300">
                <div class="item-content">
                    <div class="main-content">


                        <a href="{% url 'posts:post_detail' post.slug %}">
                            <p></p>
                            <button type="submit" class="btn btn-primary"
                                style="height:33px;width:87px;line-height: 50px">
                                <h6>Leer más</h6>
                            </button>
                        </a>-->
                        <!--
                        <ul class="post-info">
                            <p></p>
                            <p style="color: rgb(255, 255, 255) ;">{{ post.date_added }}</p>
                        </ul>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>

    </div>
</div>
VIDEO-->
<!--
<div class="main-nammer header-text">
    <div class="scale-video">

        <body>
            <hr>
            <p style="text-align:center"><video width="640" height="480" allowfullscreen="" muted autoplay>
                    <source src="{%static 'video.mp4'%}" type="video/mp4">
                </video></p>
        </body>
    </div>
</div>-->
{% endblock %}